# Generated by Django 3.1.1 on 2020-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201020_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIdCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countType', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=100)),
            ],
        ),
    ]
